import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "sonner";
import connectToDB from "@/config/db";
import { cookies } from "next/headers";
import { verifyToken } from "@/utils/auth";
import usersModel from "@/models/users";

const vazir = Vazirmatn({
  // weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["arabic", "latin"],
  display: "swap",
});

export const metadata = {
  title: "twitifa",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectToDB();
  const clientId = process.env.GOOGLE_CLIENT_ID;
  

  return (
    <html lang="fa" dir="rtl" className={`dark ${vazir.className}`}>
      <body className="bg-zinc-50 dark:bg-body ">
        <Toaster
          richColors
          position="bottom-center"
          toastOptions={{
            style: {
              minHeight: "60px",
              borderRadius: "16px",
              paddingTop: "15px",
              paddingBottom: "15px",
            },
          }}
        />
        <Providers clientId={clientId} >
          {" "}
          {children}
        </Providers>
      </body>
    </html>
  );
}
